DROP PROCEDURE IF EXISTS `addPriority`;
DELIMITER //
CREATE PROCEDURE `addPriority`()
BEGIN
    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION BEGIN END;
    ALTER TABLE process ADD COLUMN priority INT (3) DEFAULT 1;
END //
DELIMITER ;
CALL `addPriority`();
DROP PROCEDURE `addPriority`;
