DROP PROCEDURE IF EXISTS `addCreatedColumn`;
DELIMITER //
CREATE PROCEDURE `addCreatedColumn`()
BEGIN
    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION BEGIN END;
    ALTER TABLE report ADD COLUMN reportCreatedTimestamp TIMESTAMP NULL DEFAULT NULL;
END //
DELIMITER ;
CALL `addCreatedColumn`();
DROP PROCEDURE `addCreatedColumn`;
