DROP PROCEDURE IF EXISTS `changeTaskDataToJson`;
DELIMITER //
CREATE PROCEDURE `changeTaskDataToJson`()
BEGIN
    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION BEGIN END;
    ALTER TABLE report MODIFY taskData JSON;
END //
DELIMITER ;
CALL `changeTaskDataToJson`();
DROP PROCEDURE `changeTaskDataToJson`;
